-- ユーザー(スキーマ)作成
-- ※ <password> は、任意のパスワードで書き換えてください。
CREATE USER ORDER_ENTRY PASSWORD <password> NO FORCE_FIRST_PASSWORD_CHANGE SET USERGROUP DEFAULT;


-- 権限設定
GRANT CATALOG READ  TO ORDER_ENTRY  WITH ADMIN OPTION;
GRANT CREATE SCHEMA TO ORDER_ENTRY WITH ADMIN OPTION;
GRANT HANA_SYSRDL#CG_ADMIN_ROLE TO ORDER_ENTRY;


-- ビューの作成
CREATE VIEW ORDER_ENTRY.V_ORDERS AS 
  SELECT 
	d1."CUSTOMERID",
	d1."CITYID",
	d1."COUNTRYID",
	d1."REGIONID",
	d1."CUSTOMER",
	d1."CITYNAME",
	d1."COUNTRYNAME",
	d1."REGIONNAME",
	d2."PRODUCTID",
	d2."CATEGORYID",
	d2."LINEID",
	d2."PRODUCTNAME",
	d2."CATEGORYNAME",
	d2."LINENAME",
	f1."UNITSALES",
	f1."NETSALES"
  FROM "ORDER_ENTRY"."ORDERS" f1
    INNER JOIN "ORDER_ENTRY"."CUSTOMERS" d1 ON d1."CUSTOMERID" = f1."CUSTOMERID"
    INNER JOIN "ORDER_ENTRY"."PRODUCTS"  d2 ON d2."PRODUCTID"  = f1."PRODUCTID"
;

